### ISSUE TITLE
Przechodzenie do listy załączników w edytorze wiadomości

### ISSUE THREAD

**Issue by michaldziwisz** [lukaszgo1/Becky#1]
Może dałoby się dorzucić do tego jakiś skrót? Obecnie to zdaje się jedno z niewielu niedostępnych miejsc z klawiatury, wymaga używania nawigacji obiektowej.

**Comment by lukaszgo1** [comment]
Zaimplementowane w 64cfb53 - NVDA+Shift+a przenosi na listę jeżeli obecnie edytowana wiadomość ma załączniki. W zakładce Releases dostępna jest już wersja 0.2-dev z tą funkcjonalnością.
